Main:
  points:
  - x: 4.86
    y: 10.28
    zone_name: A1
  - x: 6.1
    y: 11.44
    zone_name: A2
  - x: 11.09
    y: 6.66
    zone_name: A3
  - x: 10.08
    y: 5.53
    zone_name: A4
  settings:
    loop_type: closed
    loop_mode: true
    curved_segments: []
    curved_segment_controls: {}
    direction: uni
    segment_attrs: {}
    has_curves: false
back:
  points:
  - x: 1.26
    y: -1.26
    zone_name: a1
  - x: 2.04
    y: -0.17
    zone_name: a2
  settings:
    loop_type: ping_pong
    loop_mode: true
    curved_segments: []
    curved_segment_controls: {}
    direction: uni
    segment_attrs: {}
    has_curves: false
zlef:
  points:
  - x: 11.09
    y: 6.66
    zone_name: A3
  - x: 12.06
    y: 5.41
    zone_name: PRE-POINT
  - x: 13.17
    y: 4.37
    zone_name: SHELF1
  - x: 10.08
    y: 5.53
    zone_name: A4
  settings:
    loop_type: closed
    loop_mode: true
    curved_segments: []
    curved_segment_controls: {}
    direction: uni
    segment_attrs:
      '1':
        direction: bi
    has_curves: false
zelf multiple:
  points:
  - x: 10.08
    y: 5.53
    zone_name: A4
  - x: 11.09
    y: 6.66
    zone_name: A3
  - x: 12.06
    y: 5.41
    zone_name: PRE-POINT
  - x: 13.17
    y: 4.37
    zone_name: SHELF1
  - x: 12.06
    y: 5.41
    zone_name: PRE-POINT
  - x: 10.08
    y: 5.53
    zone_name: A4
  settings:
    loop_type: none
    loop_mode: false
    curved_segments: []
    curved_segment_controls: {}
    direction: uni
    segment_attrs: {}
    has_curves: false
new:
  points:
  - x: 10.08
    y: 5.53
    zone_name: A4
  - x: 11.09
    y: 6.66
    zone_name: A3
  - x: 12.06
    y: 5.41
    zone_name: PRE-POINT
  - x: 13.17
    y: 4.37
    zone_name: SHELF1
  - x: 12.06
    y: 5.41
    zone_name: PRE-POINT
  - x: 10.08
    y: 5.53
    zone_name: A4
  - x: 6.1
    y: 11.44
    zone_name: A2
  - x: 11.09
    y: 6.66
    zone_name: A3
  settings:
    loop_type: none
    loop_mode: false
    curved_segments: []
    curved_segment_controls: {}
    direction: uni
    segment_attrs: {}
    has_curves: false
innershelf:
  points:
  - x: -2.79
    y: 0.1
    zone_name: new
  - x: -1.415
    y: 0.105
    zone_name: ins1
  - x: -0.33
    y: 0.1
    zone_name: SHELF11
  settings:
    loop_type: closed
    loop_mode: true
    curved_segments: []
    curved_segment_controls: {}
    direction: uni
    segment_attrs: {}
    has_curves: false
zelfy:
  points:
  - x: 10.08
    y: 5.53
    zone_name: A4
  - x: 11.09
    y: 6.66
    zone_name: A3
  - x: 11.747371
    y: 5.672344
    zone_name: PRE-POINT
  - x: 12.57
    y: 4.9
    zone_name: zelf
  - x: 11.747371
    y: 5.672344
    zone_name: PRE-POINT
  - x: 10.08
    y: 5.53
    zone_name: A4
  settings:
    loop_type: none
    loop_mode: false
    curved_segments: []
    curved_segment_controls: {}
    direction: uni
    segment_attrs: {}
    has_curves: false
