#!/usr/bin/env python3
"""Simple HTTP viewer for the robot SQLite database."""

from __future__ import annotations

import argparse
import html
import json
import os
import sqlite3
import socketserver
import sys
from http.server import BaseHTTPRequestHandler
from typing import List

DEFAULT_DB_PATH = os.path.expanduser("~/DB/robot_data.db")
DEFAULT_PORT = 8000
DEFAULT_REFRESH_SEC = 5


class ThreadingTCPServer(socketserver.ThreadingMixIn, socketserver.TCPServer):
    """Threaded server with reusable address to survive relaunch quickly."""

    allow_reuse_address = True
    daemon_threads = True


def _render_db_html(db_path: str, refresh_sec: int) -> str:
    safe_db_path = html.escape(db_path)
    html_out = f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="refresh" content="{int(refresh_sec)}">
  <title>Robot Data Viewer</title>
  <style>
    body {{ font-family: sans-serif; margin: 20px; background: #f0f0f0; }}
    .container {{ max-width: 1200px; margin: 0 auto; background: #fff; padding: 20px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }}
    h1 {{ border-bottom: 2px solid #333; padding-bottom: 10px; }}
    h2 {{ color: #0066cc; margin-top: 30px; }}
    table {{ border-collapse: collapse; width: 100%; margin-bottom: 20px; font-size: 14px; }}
    th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; vertical-align: top; }}
    th {{ background-color: #f2f2f2; font-weight: bold; }}
    tr:nth-child(even) {{ background-color: #fafafa; }}
    tr:hover {{ background-color: #e6f7ff; }}
    .json-data {{ background: #f9f9f9; padding: 5px; border-radius: 4px; font-family: monospace; white-space: pre-wrap; font-size: 12px; }}
    .footer {{ margin-top: 40px; font-size: 12px; color: #888; text-align: center; }}
    .error {{ color: #b00020; padding: 12px; background: #ffe6e6; border-radius: 6px; }}
  </style>
</head>
<body>
  <div class="container">
    <h1>Robot SQLite Data Viewer</h1>
    <p><strong>Database:</strong> {safe_db_path}</p>
    <p><em>Auto-refresh every {int(refresh_sec)}s.</em></p>
"""

    if not os.path.exists(db_path):
        html_out += f'<div class="error">Database file not found: {safe_db_path}</div>'
    else:
        try:
            conn = sqlite3.connect(db_path)
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()

            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
            tables = cursor.fetchall()
            if not tables:
                html_out += "<p>No tables found in database.</p>"

            for table in tables:
                table_name = str(table[0])
                safe_table = html.escape(table_name)
                html_out += f"<h2>Table: {safe_table}</h2>"

                cursor.execute(f'SELECT count(*) AS count FROM "{table_name}"')
                count = int(cursor.fetchone()["count"])
                html_out += f"<p><em>{count} records</em></p>"

                if count <= 0:
                    html_out += "<p>Empty table.</p>"
                    continue

                cursor.execute(f'PRAGMA table_info("{table_name}")')
                columns = cursor.fetchall()
                col_names: List[str] = [str(col[1]) for col in columns]

                html_out += "<table><thead><tr>"
                for col in col_names:
                    html_out += f"<th>{html.escape(col)}</th>"
                html_out += "</tr></thead><tbody>"

                cursor.execute(f'SELECT * FROM "{table_name}"')
                rows = cursor.fetchall()
                for row in rows:
                    html_out += "<tr>"
                    for col in col_names:
                        value = row[col]
                        display = html.escape(str(value))
                        if isinstance(value, str) and value[:1] in ("{", "["):
                            try:
                                parsed = json.loads(value)
                                display = (
                                    '<div class="json-data">'
                                    + html.escape(json.dumps(parsed, indent=2))
                                    + "</div>"
                                )
                            except Exception:
                                pass
                        html_out += f"<td>{display}</td>"
                    html_out += "</tr>"
                html_out += "</tbody></table>"

            conn.close()
        except Exception as exc:
            html_out += f'<div class="error">Error reading database: {html.escape(str(exc))}</div>'

    html_out += """
    <div class="footer">Generated by db_viewer.py • NextUI Robot System</div>
  </div>
</body>
</html>
"""
    return html_out


def _make_handler(db_path: str, refresh_sec: int):
    class DBViewerHandler(BaseHTTPRequestHandler):
        def do_GET(self):  # noqa: N802
            if self.path != "/":
                self.send_error(404)
                return

            payload = _render_db_html(db_path, refresh_sec).encode("utf-8", errors="replace")
            self.send_response(200)
            self.send_header("Content-type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            self.wfile.write(payload)

        def log_message(self, fmt, *args):
            # Keep launch logs cleaner.
            return

    return DBViewerHandler


def _parse_args(argv: List[str]):
    parser = argparse.ArgumentParser(description="SQLite DB web viewer")
    parser.add_argument("--db-path", default=DEFAULT_DB_PATH, help="Path to SQLite DB file")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT, help="HTTP port")
    parser.add_argument(
        "--refresh-sec",
        type=int,
        default=DEFAULT_REFRESH_SEC,
        help="Auto refresh interval seconds",
    )
    # Ignore ROS launch-injected args like --ros-args.
    args, _unknown = parser.parse_known_args(argv)
    return args


def main(argv: List[str] | None = None):
    args = _parse_args(sys.argv[1:] if argv is None else argv)
    db_path = os.path.expanduser(str(args.db_path or DEFAULT_DB_PATH))
    port = int(args.port or DEFAULT_PORT)
    refresh_sec = max(1, int(args.refresh_sec or DEFAULT_REFRESH_SEC))

    handler_cls = _make_handler(db_path=db_path, refresh_sec=refresh_sec)
    with ThreadingTCPServer(("", port), handler_cls) as httpd:
        print(f"[db_viewer] Serving DB viewer on http://localhost:{port}")
        print(f"[db_viewer] DB path: {db_path}")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            pass


if __name__ == "__main__":
    main()
